apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-messenger
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: kube-messenger
  source:
    path: k8s/k8s/helm
    repoURL: https://github.com/karimsdocto/formations-solutions/
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true